### ISSUE TITLE
WebPage: Weapon Details

### ISSUE THREAD

**Issue by TimothyMothra** [TimothyMothra/D2WeaponReport#14]
This item is tracking features I want displayed on a details page.

## Features
- Metadata
     - [x] Frame
     - [x] Type
     - [ ]  Rarity
     - [ ] Display default stats
         - [x] Display stat percentiles
     - [x] Image
- Perks
    - [x] Display table of each perk column 
        - [ ] display total and sort desc
        - [x] remove empty columns
- Permutations
    - [x] Box Plot
    - [x] List

## Todo
- [ ] Rename classes to match vocabulary of model described here.
