### ISSUE TITLE
Fix Deployments

### ISSUE THREAD

**Issue by TimothyMothra** [TimothyMothra/D2WeaponReport#27]
Currently, application is built and then deployed without database.
Application can self-init database.
This is great for local debugging, but I don't want this in production.
This can cause issues whenever API is down and database is unavailable.

##TODO
- [x] remove Artifacts from build. This is costing space.
  As a temp fix, I set artifacts to expire after 2 days.
- [x] fix application self-init. Debug only? - Disabled, will reconsider
- [x] fix deployment to correctly init database and delpoy with application
