### ISSUE TITLE
onboard to TypeScript

### ISSUE THREAD

**Issue by TimothyMothra** [TimothyMothra/D2WeaponReport#33]
- https://www.typescriptlang.org/docs/handbook/asp-net-core.html
- https://docs.microsoft.com/en-us/visualstudio/javascript/tutorial-aspnet-with-typescript?view=vs-2019

IMPORTANT:
Node is a requirement to use NPM 

### TODO
- [x] build must fail if typescript is not compiled
- [x] app.ts is not compiling to wwwroot/scripts/app.js
- [x] npm is not caching packages
- [x] typescript not publishing correctly
- [x] typescript builds and publishes correctly, but is using redundant scripts. need to investigate.
- [ ] consolidate the verify scripts in workflow. 
- [ ] migrate all existing javascript to TypeScript
